# Generated by Django 4.1.2 on 2022-10-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_remove_users_id_role_delete_role_and_more'),
        ('posts', '0003_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
